"""empty message

Revision ID: 878741db8e79
Revises: 
Create Date: 2020-05-05 15:45:28.375850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878741db8e79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presiden_blackhat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presiden_blackhat',
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
